In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/tips.csv')

In [3]:
df.head()

   total_bill   tip dessert  day    time  size
0       16.99  1.01      No  Sun  Dinner     2
1       10.34  1.66      No  Sun  Dinner     3
2       21.01  3.50      No  Sun  Dinner     3
3       23.68  3.31      No  Sun  Dinner     2
4       24.59  3.61      No  Sun  Dinner     4

In [10]:
df['dessert_bool'] = df.dessert.map({'No': 0, 'Yes': 1})

In [11]:
df.head()

   total_bill   tip dessert  day    time  size  dessert_bool
0       16.99  1.01      No  Sun  Dinner     2             0
1       10.34  1.66      No  Sun  Dinner     3             0
2       21.01  3.50      No  Sun  Dinner     3             0
3       23.68  3.31      No  Sun  Dinner     2             0
4       24.59  3.61      No  Sun  Dinner     4             0

In [12]:
# ou via get_dummies
pd.get_dummies(df['dessert']).head()

   No  Yes
0   1    0
1   1    0
2   1    0
3   1    0
4   1    0

In [7]:
# mas nao precisa dos 2 neh
pd.get_dummies(df['dessert'], prefix='Dessert').iloc[:, 1:].head()

   Dessert_Yes
0            0
1            0
2            0
3            0
4            0

In [13]:
import numpy as np

In [18]:
df = pd.DataFrame(np.arange(16).reshape(4,4), columns=['a','b','c','d'])
df['oi'] = ['x','y','w','z']
df = df.set_index(df['oi'])
df

     a   b   c   d oi
oi
x    0   1   2   3  x
y    4   5   6   7  y
w    8   9  10  11  w
z   12  13  14  15  z

In [21]:
df.iloc[1:3 , 3:5]

     d oi
oi
y    7  y
w   11  w

In [8]:
#ai tu pode ate concatenar esse negocio na tabela
dummies_dessert = pd.get_dummies(df['dessert'], prefix='Dessert').iloc[:, 1:]

In [9]:
dummies_dessert.head()

   Dessert_Yes
0            0
1            0
2            0
3            0
4            0

In [22]:
df = pd.concat([df, dummies_dessert], axis=1)

In [23]:
df.head()

   total_bill   tip dessert  day    time  size  dessert_bool  Dessert_Yes
0       16.99  1.01      No  Sun  Dinner     2             0            0
1       10.34  1.66      No  Sun  Dinner     3             0            0
2       21.01  3.50      No  Sun  Dinner     3             0            0
3       23.68  3.31      No  Sun  Dinner     2             0            0
4       24.59  3.61      No  Sun  Dinner     4             0            0

In [22]:
# mas ngm faz desse jeito
df = pd.read_csv('data/tips.csv')

In [23]:
df = pd.get_dummies(df, columns=['dessert', 'day'], drop_first=True)

In [24]:
df.head()

   total_bill   tip    time  size  dessert_Yes  day_Sat  day_Sun  day_Thur
0       16.99  1.01  Dinner     2            0        0        1         0
1       10.34  1.66  Dinner     3            0        0        1         0
2       21.01  3.50  Dinner     3            0        0        1         0
3       23.68  3.31  Dinner     2            0        0        1         0
4       24.59  3.61  Dinner     4            0        0        1         0

# Mas e que que eu faço com valores continuos?

In [7]:
pd.get_dummies(df[['day', 'size', 'dessert']], )

,1.0,1.01,1.1,1.17,1.25,1.32,1.36,1.44,1.45,1.47,...,5.65,5.85,5.92,6.0,6.5,6.7,6.73,7.58,9.0,10.0
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
215,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
216,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
217,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
218,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
219,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
220,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
221,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
222,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
223,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
224,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
225,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
226,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
227,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
228,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
229,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
230,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
231,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
232,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
233,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
234,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
235,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
236,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
237,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
238,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
239,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
240,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
241,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
242,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
243,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0